---
COMMON_TEST_CONFIG: &COMMON_TEST_CONFIG
  timeout_in_minutes: 5
  matrix:
    setup:
      gemfile:
        - Gemfile
        - gemfiles/redis_3.gemfile
        - gemfiles/redis_4.gemfile
  artifact_paths:
    - spec/reports/**/*

steps:
  - label: ":ruby: 2.7 :rspec: with {{matrix.gemfile}}"
    agents:
      queue: ruby-2-7
    env:
      BUNDLE_GEMFILE: "{{matrix.gemfile}}"
      JUNIT_OUTPUT: spec/reports/ruby-2-7/rspec.xml
    <<: *COMMON_TEST_CONFIG
    commands:
      - bundle install
      - bundle exec rspec

  - label: ":ruby: 3.0 :rspec: with {{matrix.gemfile}}"
    agents:
      queue: ruby-3-0
    env:
      BUNDLE_GEMFILE: "{{matrix.gemfile}}"
      JUNIT_OUTPUT: spec/reports/ruby-3-0/rspec.xml
    <<: *COMMON_TEST_CONFIG
    commands:
      - bundle install
      - bundle exec rspec

  - label: ":ruby: 3.1 :rspec: with {{matrix.gemfile}}"
    agents:
      queue: ruby-3-1
    env:
      BUNDLE_GEMFILE: "{{matrix.gemfile}}"
      JUNIT_OUTPUT: spec/reports/ruby-3-1/rspec.xml
    <<: *COMMON_TEST_CONFIG
    commands:
      - bundle install
      - bundle exec rspec

  # Test Summary Annotate Plugin
  - wait: ~
    continue_on_failure: true

  - label: Test Summary Annotate
    timeout_in_minutes: 5
    agents:
      queue: ruby-2-7
    plugins:
      - bugcrowd/test-summary#master:
          inputs:
            - label: Unit Tests
              artifact_path: spec/reports/**/*
              type: junit
          run_without_docker: true
